version: '3.7'
services:
  zeek:
    image: blacktop/zeek:latest
    hostname: zeek
    restart: always
    network_mode: host
    command: -i ${IF} /usr/local/zeek/share/zeek/site/local.zeek
    volumes:
      - /var/log/zeek:/pcap
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW 
  suricata:
    image: jasonish/suricata:latest
    hostname: suricata
    restart: always
    network_mode: host
    volumes:
      - /var/log/suricata:/var/log/suricata
      - ./files/rules:/etc/suricata/rules
      - ./files/suricata.yaml:/etc/suricata/suricata.yaml
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW 
    command:
      -  /usr/bin/suricata -c /etc/suricata/suricata.yaml -s /etc/suricata/rules/*.rules -i ${IF}
