version: '3.7'
services:
  zeek:
    image: zeek:customeV5
    hostname: zeek
    restart: always
    network_mode: host
    command: -i ${INT} /usr/local/zeek/share/zeek/site/local.zeek
    volumes:
      - /var/log/zeek:/pcap
  suricata:
    image: jasonish/suricata:latest
    hostname: suricata
    restart: always
    network_mode: host
    volumes:
      - /var/log/suricata
      - /var/lib/suricata
      - /etc/suricata 
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
