version: '3.7'
services:
  zeek:
    image: blacktop/zeek:latest
    hostname: zeek
    restart: always
    network_mode: host
    command: -i enp2s0 /usr/local/zeek/share/zeek/site/local.zeek
    volumes:
      - ./zeek-logs:/pcap
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW 
  suricata:
    image: jasonish/suricata:latest
    hostname: suricata
    restart: always
    network_mode: host
    volumes:
      - ./suricata-logs:/var/log/suricata
      - ./suricata-rules:/etc/suricata
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW 
    command:
      -  /usr/bin/suricata -i enp2s0
